name: Generate README

on:
  push:
    paths:
      - 'src/**/*.java'        # si modifico alguna clase generamos el readme
      - 'src/**/*.feature'     # si modifico algún feature generamos el readme
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # necesario para hacer commit del README

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run README generator
        run: python generate_readme.py

      - name: Commit README actualizado
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "docs: auto-update README con métodos de BasePage"
          git push